"""Add organizations and RBAC

Revision ID: ac4f26b751bf
Revises: 419a5226476f
Create Date: 2026-02-27 09:50:33.129766

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac4f26b751bf'
down_revision: Union[str, None] = '419a5226476f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_members',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.add_column('chats', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chats_org_id'), 'chats', ['org_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('repositories', sa.Column('org_id', sa.UUID(), nullable=True))
    op.alter_column('repositories', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_repositories_org_id'), 'repositories', ['org_id'], unique=False)
    op.create_foreign_key(None, 'repositories', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_index(op.f('ix_repositories_org_id'), table_name='repositories')
    op.alter_column('repositories', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('repositories', 'org_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_org_id'), table_name='chats')
    op.drop_column('chats', 'org_id')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
