"""Offline seed script for DevIntel AI demo repository.

Creates or ensures the demo user (demo@devintel.dev) exists and indexes a real,
bounded scope of backend code (app/ai, app/services, app/models) through the real
smart_chunk_code pipeline and real Gemini embedding provider call.

Health scores are generated by calling CodeHealthService.analyze() — the same
pipeline used during real indexing — NOT hardcoded values.

Idempotent: check-then-insert/skip. Re-running is a clean no-op.
"""

import asyncio
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# Add backend root to sys.path
BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))

from sqlalchemy import select, func
from app.db.session import AsyncSessionLocal
from app.core.security import hash_password
from app.models.repository import Repository, IndexingStatus
from app.models.embedding import Embedding
from app.models.architecture import ArchitectureDiagram
from app.repositories.user_repo import UserRepository
from app.repositories.repository import RepositoryRepository
from app.repositories.embedding import EmbeddingRepository
from app.repositories.code_health import CodeHealthRepository
from app.repositories.architecture import ArchitectureDiagramRepository
from app.services.embedding import EmbeddingService
from app.utils.chunking import smart_chunk_code
from app.core.config import settings

DEMO_EMAIL = "demo@devintel.dev"
DEMO_PASSWORD = "DemoUser1!"
DEMO_FULL_NAME = "Demo User"
DEMO_REPO_NAME = "devintel-core"
DEMO_REPO_FULL_NAME = "devintel/devintel-core"


def collect_code_chunks() -> list[tuple[str, int, str]]:
    """
    Parse real code files from bounded scope (app/ai, app/services, app/models)
    and chunk them using the real smart_chunk_code pipeline.
    """
    targets = [
        BACKEND_DIR / "app" / "ai",
        BACKEND_DIR / "app" / "services",
        BACKEND_DIR / "app" / "models",
    ]

    all_chunks: list[tuple[str, int, str]] = []
    scanned_files = 0

    for target_dir in targets:
        if not target_dir.exists():
            continue
        for root, _dirs, files in os.walk(target_dir):
            if "__pycache__" in root:
                continue
            for file_name in sorted(files):
                if not file_name.endswith(".py") or file_name.startswith("__"):
                    continue
                file_path = Path(root) / file_name
                rel_path = str(file_path.relative_to(BACKEND_DIR)).replace("\\", "/")

                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                        code = f.read()
                    if not code.strip():
                        continue

                    file_chunks = smart_chunk_code(code, rel_path)
                    for chunk_idx, chunk_text in enumerate(file_chunks):
                        all_chunks.append((rel_path, chunk_idx, chunk_text))
                    scanned_files += 1
                except Exception as e:
                    print(f"Warning: Failed to chunk {rel_path}: {e}")

    print(f"  [Parser] Scanned {scanned_files} Python source files across app/ai, app/services, app/models")
    return all_chunks


async def seed_demo():
    """Main seed function."""
    start_time = time.time()
    print("=" * 70)
    print("DevIntel AI — Demo Repository Offline Seeder")
    print("=" * 70)

    async with AsyncSessionLocal() as session:
        user_repo = UserRepository(session)
        repo_repo = RepositoryRepository(session)
        embedding_repo = EmbeddingRepository(session)
        health_repo = CodeHealthRepository(session)
        arch_repo = ArchitectureDiagramRepository(session)

        # 1. Ensure demo user exists
        print("\n1. Checking Demo User...")
        user = await user_repo.get_by_email(DEMO_EMAIL)
        if not user:
            print(f"  Creating demo user: {DEMO_EMAIL} ({DEMO_FULL_NAME})")
            user = await user_repo.get_or_create_demo_user(
                email=DEMO_EMAIL,
                hashed_password=hash_password(DEMO_PASSWORD),
                full_name=DEMO_FULL_NAME,
            )
            await session.commit()
            print(f"  Demo user created with ID: {user.id}")
        else:
            print(f"  Demo user exists: ID={user.id} ({user.email})")

        # 2. Check if demo repository already exists
        print("\n2. Checking Demo Repository...")
        repo = await repo_repo.get_by_full_name(DEMO_REPO_FULL_NAME, user_id=user.id)

        if repo and repo.indexing_status == IndexingStatus.COMPLETE:
            # Check embedding count — only skip if fully seeded
            emb_count_res = await session.execute(
                select(func.count()).select_from(Embedding).where(Embedding.repo_id == repo.id)
            )
            emb_count = emb_count_res.scalar_one()

            # Collect expected chunk count to check completeness
            expected_chunks = len(collect_code_chunks())
            if emb_count >= expected_chunks:
                print(
                    f"\n[IDEMPOTENT] Demo repository '{DEMO_REPO_FULL_NAME}' (ID: {repo.id}) "
                    f"is already seeded with {emb_count}/{expected_chunks} embeddings."
                )
                print("No changes needed. Skipping.\n")
                return
            else:
                print(f"  Repository exists but incomplete: {emb_count}/{expected_chunks} embeddings. Resuming...")

        # 3. Create or update repository record
        if not repo:
            print(f"  Creating repository record: {DEMO_REPO_FULL_NAME}")
            repo = await repo_repo.create(
                user_id=user.id,
                full_name=DEMO_REPO_FULL_NAME,
                repo_name=DEMO_REPO_NAME,
                description="DevIntel AI Core - Intelligent Repository Intelligence & AI Assistant Platform",
                url=f"https://github.com/{DEMO_REPO_FULL_NAME}",
                stars=142,
                language="Python",
                default_branch="main",
                indexing_status=IndexingStatus.INDEXING,
                indexing_progress=10,
                indexing_mode="standard",
            )
            await session.commit()
            print(f"  Repository created with ID: {repo.id}")
        else:
            print(f"  Found incomplete repository: ID={repo.id}, updating...")
            await repo_repo.update(
                repo.id,
                indexing_status=IndexingStatus.INDEXING,
                indexing_progress=10,
            )
            await session.commit()

        # 4. Chunk code using real pipeline
        print("\n3. Chunking Source Code with smart_chunk_code...")
        chunks = collect_code_chunks()
        print(f"  Generated {len(chunks)} real code chunks.")

        if not chunks:
            raise RuntimeError("No code chunks generated! Check search paths.")

        # 5+6. Generate embeddings and store incrementally (resumable)
        print("\n4. Generating & Storing Embeddings (resumable, Gemini)...")

        # Check which chunks are already embedded (for resume support)
        existing_paths_res = await session.execute(
            select(Embedding.file_path, Embedding.chunk_index).where(
                Embedding.repo_id == repo.id
            )
        )
        already_done = {(r[0], r[1]) for r in existing_paths_res.fetchall()}
        remaining = [(fp, ci, ct) for fp, ci, ct in chunks if (fp, ci) not in already_done]

        print(f"  Total chunks: {len(chunks)}, Already embedded: {len(already_done)}, Remaining: {len(remaining)}")

        if remaining:
            embedding_service = EmbeddingService()
            batch_size = 5
            total_inserted = len(already_done)

            for batch_start in range(0, len(remaining), batch_size):
                batch = remaining[batch_start:batch_start + batch_size]
                batch_texts = [ct for _, _, ct in batch]

                try:
                    response = await embedding_service.orchestrator.embed_batch(
                        batch_texts, agent="embedding"
                    )
                    batch_embeddings = response.embeddings

                    # Insert this batch immediately
                    batch_data = []
                    for (fp, ci, ct), emb in zip(batch, batch_embeddings):
                        batch_data.append({
                            "repo_id": repo.id,
                            "file_path": fp,
                            "chunk_index": ci,
                            "chunk_text": ct,
                            "embedding": emb,
                        })
                    await embedding_repo.create_bulk(batch_data)
                    await session.commit()
                    total_inserted += len(batch_data)
                    emb_dim = len(batch_embeddings[0])
                    print(f"    Batch {batch_start // batch_size + 1}: "
                          f"{total_inserted}/{len(chunks)} embeddings ({emb_dim}-dim)")

                    # Rate limit delay
                    import asyncio as _asyncio
                    await _asyncio.sleep(10)

                except Exception as e:
                    await session.commit()  # Save progress so far
                    print(f"\n  [RATE LIMITED] Saved {total_inserted}/{len(chunks)} embeddings so far.")
                    print(f"  Error: {e}")
                    print(f"  Re-run this script to resume from where it left off.\n")
                    return

        # Verify final count
        final_count_res = await session.execute(
            select(func.count()).select_from(Embedding).where(Embedding.repo_id == repo.id)
        )
        final_count = final_count_res.scalar_one()
        print(f"  All {final_count} embeddings stored successfully.")

        # 7. Run REAL Code Health Analysis via CodeHealthService pipeline
        print("\n6. Running Real Code Health Analysis (CodeHealthService.analyze)...")
        from app.services.code_health_service import CodeHealthService
        health_service = CodeHealthService()
        health_start = time.time()
        health_result = await health_service.analyze(
            repository=repo,
            embedding_repo=embedding_repo,
            health_repo=health_repo,
        )
        health_duration = time.time() - health_start
        print(f"  Code health analysis completed in {health_duration:.2f}s.")
        print(f"  Overall Score:        {health_result.get('overall_score', 'N/A')}")
        print(f"  Complexity Score:     {health_result.get('complexity_score', 'N/A')}")
        print(f"  Documentation Score:  {health_result.get('documentation_score', 'N/A')}")
        print(f"  Maintainability:      {health_result.get('maintainability_score', 'N/A')}")
        print(f"  Test Coverage:        {health_result.get('test_coverage_score', 'N/A')}")
        print(f"  Security Score:       {health_result.get('security_score', 'N/A')}")
        print(f"  Summary:              {health_result.get('summary', 'N/A')[:120]}...")

        # 8. Generate REAL Architecture Diagram from stored embeddings
        print("\n7. Generating Real Architecture Diagram (from stored embeddings)...")
        from app.services.architecture_service import CodeStructureAnalyzer, ArchitectureVisualizationService

        arch_analyzer = CodeStructureAnalyzer()
        arch_structure = await arch_analyzer.from_embeddings(
            repo_id=repo.id,
            session=session,
        )
        arch_service = ArchitectureVisualizationService(session)
        mermaid_code = arch_service._generate_mermaid_from_structure(arch_structure, "mermaid")

        print(f"  Modules found:  {len(arch_structure.get('modules', {}))}")
        print(f"  Edges found:    {len(arch_structure.get('edges', []))}")
        stats = arch_structure.get("stats", {})
        print(f"  Total classes:  {stats.get('total_classes', 0)}")
        print(f"  Total functions:{stats.get('total_functions', 0)}")
        if arch_structure.get("capping_note"):
            print(f"  Capping note:   {arch_structure['capping_note']}")

        # Delete any existing diagrams and replace with real one
        existing_diagrams = await arch_repo.get_by_repo(repo.id)
        if existing_diagrams:
            await arch_repo.delete_by_repo(repo.id)
            print("  Replaced old static diagram.")
        await arch_repo.create(
            repo_id=repo.id,
            name="DevIntel Core Architecture",
            diagram_type="mermaid",
            mermaid_code=mermaid_code,
        )
        print("  Real architecture diagram created successfully.")

        # 9. Mark Repository as COMPLETE
        print("\n8. Finalizing Repository Status...")
        await repo_repo.update(
            repo.id,
            indexing_status=IndexingStatus.COMPLETE,
            indexing_progress=100,
            indexing_error=None,
            last_indexed_at=datetime.now(timezone.utc),
        )
        await session.commit()
        print(f"  Repository '{DEMO_REPO_FULL_NAME}' marked as COMPLETE (progress: 100%).")

    total_time = time.time() - start_time
    print("\n" + "=" * 70)
    print(f"SUCCESS: Demo repository seeded successfully in {total_time:.2f}s!")
    print(f"  Repository ID: {repo.id}")
    print(f"  Full Name:     {DEMO_REPO_FULL_NAME}")
    print(f"  Chunks/Vectors:{final_count}")
    print(f"  Embedding Dim: {settings.EMBEDDING_DIMENSIONS}")
    print(f"  Health Score:  {health_result.get('overall_score', 'N/A')}/100 (real pipeline)")
    print(f"  User:          {DEMO_EMAIL}")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    asyncio.run(seed_demo())
