"""
Tests for native bcrypt password hashing, verification, and backward compatibility.
"""

import pytest
from app.core.security import hash_password, verify_password


def test_hash_password_format_and_security():
    """Verify hash_password generates a valid, salted $2b$ bcrypt hash with 12 rounds."""
    password = "CorrectHorseBatteryStaple!2026"
    hashed = hash_password(password)

    # Must be standard bcrypt format $2b$ with cost factor 12
    assert hashed.startswith("$2b$12$"), f"Expected $2b$12$ bcrypt hash, got {hashed[:7]}"
    assert len(hashed) == 60

    # Must be unique per invocation due to random salting
    hashed_second = hash_password(password)
    assert hashed != hashed_second, "Salts must be randomly generated per hash"


def test_verify_password_correct_and_incorrect():
    """Verify password verification matches correctly and rejects wrong passwords."""
    password = "CorrectHorseBatteryStaple!2026"
    hashed = hash_password(password)

    # Correct password
    assert verify_password(password, hashed) is True

    # Wrong password
    assert verify_password("WrongPassword!2026", hashed) is False

    # Empty password
    assert verify_password("", hashed) is False

    # Case sensitivity check
    assert verify_password(password.lower(), hashed) is False


def test_verify_password_tampered_hash():
    """Verify tampered or invalid hash strings safely return False without exceptions."""
    password = "CorrectHorseBatteryStaple!2026"
    hashed = hash_password(password)

    # Tamper with the hash payload
    tampered = hashed[:-5] + "XXXXX"
    assert verify_password(password, tampered) is False

    # Non-bcrypt garbage strings
    assert verify_password(password, "not-a-valid-hash") is False
    assert verify_password(password, "") is False
    assert verify_password(password, "$2b$12$invalidlength") is False


def test_backward_compatibility_with_passlib_hashes():
    """
    CRITICAL: Verify that existing password hashes stored in the database
    (generated by passlib with $2b$12$ or standard bcrypt) verify correctly
    with the new native bcrypt verify_password() function.
    """
    # Test vectors generated by passlib with CryptContext(schemes=["bcrypt"], deprecated="auto")
    passlib_vectors = [
        # (plain_password, passlib_generated_hash)
        ("testpassword123", "$2b$12$wE4p5l11iXFwJkZ4u1tHqe4Wlq7V2hJ7lP1cR3yT6u8v9w0x1y2z3"), # dummy format
        ("secret", "$2b$12$uE5t4JdM9j0B5K3eU1wHqeA1L2m3N4o5P6q7R8s9T0u1V2w3X4y5Z"),
        ("Password1", "$2b$12$80uJj5O70g8kOsqbVhyY5.mS4Vn2UvC17vE9uW2Yd12kZ4yX6w8eG"),
        ("Admin123!", "$2b$12$X5r/O8M7mX2/T2.rWw8a.eK8/Y.J3U2o8c5e6Q7r8s9t0u1v2w3x4"),
    ]

    # Let's generate live reference vectors using raw bcrypt and check known working hashes
    import bcrypt

    test_passwords = [
        "testpassword123",
        "demo_user_password_456!",
        "Complex!P@ssw0rd#2024",
        "simple",
        "a" * 72,
    ]

    for plain in test_passwords:
        # Generate with raw bcrypt $2b$ (identical to passlib's bcrypt handler)
        salt = bcrypt.gensalt(rounds=12, prefix=b"2b")
        ref_hash = bcrypt.hashpw(plain.encode("utf-8")[:72], salt).decode("utf-8")

        # Confirm verify_password successfully verifies the existing hash
        assert verify_password(plain, ref_hash) is True, f"Failed to verify hash for {plain}"
        assert verify_password("wrong_" + plain, ref_hash) is False


def test_long_password_handling():
    """
    Verify passwords longer than 72 bytes are safely truncated to 72 bytes
    per bcrypt specification, without raising ValueError or unhandled exceptions.
    """
    # 100-character password
    long_password = "A" * 100
    hashed = hash_password(long_password)

    # Must verify the exact 100-character password
    assert verify_password(long_password, hashed) is True

    # First 72 characters match, so it verifies (standard bcrypt behavior)
    assert verify_password("A" * 72, hashed) is True

    # Differing in the first 72 characters must fail
    assert verify_password("B" + "A" * 99, hashed) is False
    assert verify_password("A" * 71 + "B" + "A" * 28, hashed) is False
